services:
    mail.queue_manager:
        class: Jasuwienas\MailBundle\Service\QueueManagerService
        arguments: [@doctrine.orm.entity_manager]
    mail.queue_manager.process:
        class: Jasuwienas\MailBundle\Service\ProcessQueueService
        arguments: [@mail.queue_manager, @service_container, @translator]
    mail.sender.smtp:
        class: Jasuwienas\MailBundle\Service\Senders\SmtpMailSenderService
        arguments: [@mailer, '%smtp_mailer_user%']
    mail.sender.freshmail:
        class: Jasuwienas\MailBundle\Service\Senders\FreshMailSenderService
        arguments: ['%freshmail_api_host%', '%freshmail_api_prefix%', '%freshmail_api_api_key%', '%freshmail_api_secret_key%']